<div class="mobilers">
    <a href="#">
        <img src="<?php print '/public/timthumb.php?src=' . $this->baseUrl . '/public/uploads/users/' . $this->mobiler['photo_url']; ?>&w=165&h=165&zc=1" alt="<?php print $this->mobiler['username']; ?>"/>
    </a>
    <h2>Név: <?php print $this->mobiler["username"]; ?></h2>
    <div style="position: relative; left: -50px; top: -30px; background: url('/public/skins/mobilers/images/block-icons.png') 0px -335px no-repeat;width: 30px; height: 20px;text-indent: 25px; float: right;"><a class="mailto" style="color: #5E6A71; position: relative; top: 3px;" href="mailto:<?php print $this->mobiler['email']; ?>">Üzenet</a></div>
    <p class="data">Kor: <?php print date("Y", time()) - $this->mobiler["birth_year"]; ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Foglalkozás: <?php print $this->mobiler["job"]; ?></p>
    <p><?php print $this->mobiler["bio"]; ?></p>
</div>

<a class="tab" href="/mobilers/profile/index/user/<?php print $this->id; ?>/tab/posts">Posztok</a>
<a class="tab" href="/mobilers/profile/index/user/<?php print $this->id; ?>/tab/comments">Kommentek</a>
<div class="clearbar"></div>
<!-- <div id="post-comments"> -->
<?php if (count($this->comments)): ?>
<?php foreach ($this->comments as $comment): ?>
        <div class="comment-node">
            <p class="comment-body"><?php echo nl2br(strip_tags($comment['description'])); ?></p>
        </div>
        <div class="comment-info">
            <span class="time"><?php print (int) ((time() - $comment["date"]) / 86400) ?> napja</span>
        </div>

<?php endforeach; ?>
<div class="clear"></div>
        <div class="pagination" style="top: 10px;">
    <?php echo $this->paginationControl($this->comments, 'Sliding', '/partials/_pagination-control.phtml'); ?>
    </div>
<?php endif; ?>

<?php if (count($this->posts)): ?>
<?php foreach ($this->posts as $post): ?>
                <div class="topic">
                    <div class="post-cover">
                        <img src="<?php print '/public/timthumb.php?src=' . $this->baseUrl . '/public/uploads/posts/' . $post['photo']; ?>&w=210&h=200&zc=1" alt="<?php print $post['title']; ?>"
                             title="<?php print $post['title']; ?>" />
                    </div>
                    <div class="post-column">
                        <div class="post-info"><?php print $post['comments']; ?> komment
            <?php echo substr($post['date'], 0, 10); ?> </div>
            <div class="post-title"><h2><a href="<?php echo $this->baseUrl() . "/posts/view/id/" . $post['post_id']; ?>"><?php echo $this->escape($post['title']); ?></a></h2></div>
            <div class="description"><?php echo nl2br(strip_tags($post['lead'])); ?></div>

            <a class="morebutton"href="/posts/view/id/<?php print $post['post_id']; ?>">TOVÁBB >></a>
        </div>
    </div>
    <div class="clear"></div>
<?php endforeach; ?>
                <div class="pagination" style="top: 10px;">
    <?php echo $this->paginationControl($this->posts, 'Sliding', '/partials/_pagination-control.phtml'); ?>
            </div>
<?php endif; ?>
            