<form class="newpassword" id="newpassword_form" method="POST" action="">
    <div class="column">        
        <div>
            <label>Új jelszó:</label>
            <?php print $this->element->password_reg; ?>
        </div>
        <div>
            <label>Új jelszó mégegyszer:</label>
            <?php print $this->element->password_reg_confirm; ?>
        </div>

    </div>
    <div class="bottom">        
        <?php print $this->element->submit; ?>
        <div class="clear"></div>
    </div>
    <span id="msgbox" style="display:none"></span>
</form>
