<form method="post" action="/suggest/index">
    <table width="207">
        <tr>
            <td align="center" colspan="2" class="title">Ajánlja a kalkulátort ismerőseinek:</td>
        </tr>
        <tr>
            <td class="form_label">Név:</td>
            <td><?php print $this->element->name; ?></td>
        </tr>
        <tr>
            <td class="form_label">E-mail:</td>
            <td><?php print $this->element->email; ?></td>
        </tr>
        <tr>            
            <td colspan="2" align="center"><br/><?php print $this->element->küldés; ?></td>
        </tr>
    </table>
</form>