<h2 class="title_h2_text" style="color:#ffa12d;">A Weboldal Használatának Feltételei</h2>
                    <br/>
                    <h2 class="title_h2_text">Engedélyezett Használat</h2>
                    <p class="etc_desc">A Weboldalhoz történő hozzáférésnek és használatának feltétele, hogy Ön egyetértsen, és maradéktalanul betartsa az alábbi feltételeket. A Weboldal használata kizárólag a feltételek betartása mellett engedélyezett. A Samsung Electronics Magyar Zrt. („Samsung”) fenntartja a jogot arra, hogy azon személyek a Weboldalhoz történő hozzáférését és felhasználását korlátozza, akikről úgy véli, hogy nem tartják be ezen feltételeket. Felhívjuk a figyelmet arra, hogy a Samsung bármikor módosíthatja a Weboldalon megjelenő információkat, ideértve a használati feltételeket is. </p>
                    <br/>

                    <h2 class="title_h2_text">Bemutatkozunk</h2>
                    <p class="etc_desc">A Weboldalt a Samsung működteti, mely a Fővárosi Bíróság Cégbírósága által Cg.01-10-041285 cégjegyzékszámon bejegyzett társaság, és amelynek székhelye 5126 Jászfényszaru, Samsung tér 1. alatt található. Minden "mi", "mienk" és "minket" hivatkozás a Samsungra vonatkozik.</p>
                    <br/>


                    <h2 class="title_h2_text">Kizárólag Magyarországi Ügyfeleknek</h2>
                    <p class="etc_desc">A Weboldalunkon megjelenő információk és szolgáltatások kizárólag olyan személyeknek szólnak, akik az oldalra Magyarországról lépnek be. Üzleti tevékenységünkre és az általunk felajánlott szolgáltatásokra a magyar jog az irányadó. Nem vállalunk felelősséget azért, illetve nem szavatoljuk, hogy a Weboldalon megjelenő információk, az általunk vagy nevünkben felajánlott szolgáltatások, ezen szolgáltatásokra és üzleti tevékenységünkre vonatkozó információk megfelelnek olyan más ország jogszabályainak, melyek nem érintik ezen információkat és szolgáltatásokat, illetve ezekre nem irányadók.</p>
                    <br/>

                    <h2 class="title_h2_text">Felelősség Kizárása</h2>
                    <p class="etc_desc">Törekszünk arra, hogy Weboldalunk tartalma mind technikailag, mind a tények szempontjából pontos legyen, azonban ezt mégsem tudjuk garantálni, ezért a Weboldalon előfordulhatnak hibák. Felelősségünk az alábbiak szerint kizárt és/vagy korlátozott.</p>
                    <br/>

                    <h2 class="title_h2_text">Szerzői Jog És Reprodukció</h2>
                    <p class="etc_desc">A Weboldalon megjelenő minden szerzői jogi alkotás, védjegy és egyéb szellemi alkotás a Samsung vagy a részünkre felhasználást engedélyező személy tulajdona. A Weboldal tartalmának bármely része kizárólag személyes és nem üzleti célra használható fel. A fentiekben meghatározott eseteket kivéve, a Weboldal tartalmának, a Weboldalon megjelenő szoftvereknek vagy információknak a módosítása, felhasználásának engedélyezése, átruházása, eladása vagy átdolgozása, feldolgozása tilos. A Weboldalon található szoftvereket szerzői jog védi, és kizárólag az adott szoftver felhasználási feltételeinek betartásával alkalmazható, és kizárólag a jelen Weboldal rendeltetésszerű használatának céljaira használhatók fel.</p>
                    <br/>

                    <h2 class="title_h2_text">Linkek</h2>
                    <p class="etc_desc">További információk elérésének megkönnyítése érdekében Weboldalunkon más weboldalakra kapcsolódó linkeket helyeztünk el. Ez azonban nem jelenti azt, hogy ezen weboldalak vagy az ott elérhető anyagok tartalmával egyetértünk, vagy azokat jóváhagyjuk, továbbá a Samsung nem vállal felelősséget ezen oldalak tartalmáért, illetve azok adatvédelmi szabályaiért.</p>
                    <br/>

                    <h2 class="title_h2_text">Vegyes Rendelkezések</h2>
                    <p class="etc_desc">A jelen Weboldal használatára a magyar jog az irányadó, és a Weboldal használatával Ön jóváhagyja Budapest, Magyarország bíróságainak kizárólagos illetékességét az Ön és cégünk között felmerülő jogvitákban. Amennyiben a használati feltételek valamely része érvénytelennek vagy jogellenesnek minősülne, akkor azt a jelen feltételekből eltávolítjuk, de a többi rendelkezés továbbra is érvényes marad.</p>
                    <br/>

                    <h2 class="title_h2_text">Ügyfélszolgálat</h2>
                    <p class="etc_desc">Amennyiben az általunk forgalmazott termékekkel és/vagy szolgáltatásokkal kapcsolatban bármilyen kérdése van, látogassa meg GY.I.K.-rovatunkat, amennyiben a Weboldallal kapcsolatosan van kérdése, írjon e-mailt az info@carpedm.hu címre. </p>
