<script type="text/javascript" src="/public/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    function textCounter( field, countfield, maxlimit ) {
        if ( field.value.length > maxlimit )
        {
            field.value = field.value.substring( 0, maxlimit );
            return false;
        }        
    }

    tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        editor_selector : "mceEditor",
        editor_deselector : "mceNoEditor",
        plugins : "style,layer,preview,media,paste,fullscreen,advimage,advlink,media,ibrowser",
        valid_elements : "a[align|href|target=_blank],strong/b,br,h2,h3,p[align],em,u,i,img[align|alt|border|class|height|hspace|idlang|name|src|style|title|vspace|width],ul,li",
        // Theme options
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,bullist,|,cut,copy,paste,pastetext,pasteword,|,undo,redo,|,link,unlink,code,insertfile,insertimage,ibrowser",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        theme_advanced_buttons4 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : false,
        entity_encoding : "raw",

        // Skin options
        skin : "o2k7",
        skin_variant : "silver",

        // Example content CSS (should be your site CSS)
        content_css : "/public/skins/mobilers/css/typo.css",

        // Drop lists for link/image/media/template dialogs
        template_external_list_url : "js/template_list.js",
        external_link_list_url : "js/link_list.js",
        external_image_list_url : "js/image_list.js",
        media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
            username : "Some User",
            staffid : "991234"
        }
    });
</script>
<h2>Új bejegyzés</h2>
<div><?php echo $this->postForm; ?></div>
