<p><span style="background: #E2E2E2;">&nbsp&nbsp;&nbsp;</span> - Aktív bejegyzés</p><br/>
<table class="adminlist" border="0" width="100%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr >
            <th class="title">Cím</th>
            <th>Topic</th>
            <th>Dátum</th>
            <th>Kommentek</th>
            <th>&nbsp;</th>
        </tr>
        <?php
        foreach ($this->posts as $p) {
            if ($p["active"] == "1") {
        ?>
                <tr align="center" style="background-color: #E2E2E2;">
            <?php } else {
            ?>
            <tr align="center">
            <?php } ?>
            <td class="title"><a href="/posts/view/id/<?php print $p["post_id"]; ?>"><?php print $p["title"]; ?></a></td>
            <td><?php print $p["topic"]; ?></td>
            <td><?php print $p["date"]; ?></td>
            <td><?php print $p["comments"]; ?></td>
            <td class="options-width">
                <a href="<?php print $this->url(array('controller' => 'posts', 'action' => 'adminedit', 'id' => $p["post_id"])); ?>" class="icon-1 info-tooltip"></a>
                <a href="<?php print $this->url(array('controller' => 'posts', 'action' => 'edit', 'id' => $p["post_id"])); ?>">Módosít</a>
        </tr>
        <?php } ?>
    </tbody>
</table>

<link rel="stylesheet" href="/public/css/tablesorter.css" type="text/css" media="print, projection, screen" />
<script type="text/javascript" src="/public/js/jquery.tablesorter.js"></script>
<script type="text/javascript" src="/public/js/jquery.tablesorter.pager.js"></script>

<script type="text/javascript">
    $(function() {
        $("#table")
        .tablesorter({widthFixed: true,
            headers: {                
                4: {
                    sorter: false
                }
            }
        })
        .tablesorterPager({container: $("#pager")});
    });
</script>

<?php if ($this->postsAdmin) {
 ?>
            <br/>
            <h2>Összes bejegyzés</h2>
            <table id="table" cellspacing="1" class="adminlist tablesorter" border="0" width="100%" cellpadding="0">
                <thead>
                    <tr>
                        <th class="title">Cím</th>
                        <th>Topic</th>
                        <th>Dátum</th>
                        <th>Mobiler</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
    <?php
            foreach ($this->postsAdmin as $p) {
                if ($p["active"] == "1") {
    ?>
                    <tr align="center" style="background-color: #E2E2E2 !important;">
<?php } else { ?>
                <tr align="center" style="background-color: #FFF !important;">
<?php } ?>
                <td class="title"><a href="/posts/view/id/<?php print $p["post_id"]; ?>"><?php print $p["title"]; ?></a></td>
                <td><?php print $p["topic"]; ?></td>
                <td><?php print $p["date"]; ?></td>
                <td><?php print $p["username"]; ?></td>
                <td class="options-width">
                    <a class="edit" href="<?php print $this->url(array('controller' => 'posts', 'action' => 'edit', 'id' => $p["post_id"])); ?>"></a>
<?php if ($p["edited"] == "1") { ?>
                    <a class="edited active" href="<?php print $this->url(array('controller' => 'posts', 'action' => 'setunedited', 'id' => $p["post_id"])); ?>"></a>
<? } else { ?>
                    <a class="edited" href="<?php print $this->url(array('controller' => 'posts', 'action' => 'setedited', 'id' => $p["post_id"])); ?>"></a>
<?php } ?>
            </td>
        </tr>
<?php } ?>
        </tbody>
        </table>
        <div id="pager" class="pager">
            <form>
                <img src="/public/skins/mobilers/images/first.png" class="first"/>
                <img src="/public/skins/mobilers/images/prev.png" class="prev"/>
                <input type="text" class="pagedisplay"/>
                <img src="/public/skins/mobilers/images/next.png" class="next"/>
                <img src="/public/skins/mobilers/images/last.png" class="last"/>
                <select class="pagesize">
                    <option selected="selected"  value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option  value="40">40</option>
                </select>
            </form>
        </div>        
<?php } ?>

