<?php foreach ($this->post as $post): ?>
    <img src="<?php print '/image/resize?filename=' . $this->baseUrl . '/public/uploads/users/' . $post['photo_url']; ?>&width=20&height=25" alt="<?php print $post['username']; ?>"
         title="<?php print $post['username']; ?>" style="float:left; margin-right:10px;" />
     <?php print $post["username"] ?>
<br/>
<br/>
<?php print $post['date']; ?>
     <br/>
     Comments ( <?php print $post['comments']; ?> )

     <img src="<?php print '/image/resize?filename=' . $this->baseUrl . '/public/uploads/posts/' . $post['photo']; ?>&width=60&height=60" alt="<?php print $post['title']; ?>"
          title="<?php print $post['title']; ?>" style="float:left; margin-right:10px;" />
     <div class="title"><?php echo $post['title']; ?></div>
     <div class="description"><?php echo $post['lead']; ?></div>
     <div class="description"><?php echo $post['content']; ?></div>
     <div class="description">
    <?php
     $video = Model_Youtube::generateEmbed($post['video']);
     print $video;
    ?>
 </div>
 <div>
     <ul>
        <?php foreach ($this->tags as $tags): ?>
            <li><?php print $tags["tag"]; ?></li>
        <?php endforeach; ?>
        </ul>
    </div>

    <link rel="stylesheet" type="text/css" href="/public/skins/mobilers/css/jqcarousel.css" />
    <script type="text/javascript" src="/public/js/jquery.jcarousel.min.js"></script>
    <script type="text/javascript">
        function mycarousel_initCallback(carousel)
        {
            // Disable autoscrolling if the user clicks the prev or next button.
            carousel.buttonNext.bind('click', function() {
                carousel.startAuto(0);
            });

            carousel.buttonPrev.bind('click', function() {
                carousel.startAuto(0);
            });

            // Pause autoscrolling if the user moves with the cursor over the clip.
            carousel.clip.hover(function() {
                carousel.stopAuto();
            }, function() {
                carousel.startAuto();
            });
        };

        jQuery(document).ready(function() {
            jQuery('#mycarousel').jcarousel({
                auto: 2,
                wrap: 'last',
                initCallback: mycarousel_initCallback
            });
        });
    </script>
    <ul id="mycarousel" class="jcarousel-skin-tango">
    <?php
            foreach ($this->picasaArray as $pic):

                //echo '<img src="' . $pic['url'] . '" alt="' . $pic["title"] . '" width="' . $pic['width'] . '" height="' . $pic['height'] . '"/>';
                print '<li><img src="' . $pic['url'] . '" alt="' . $pic["title"] . '" width="75" height="75" /></li>';
            endforeach;
    ?>
        </ul>


        <!-- "next page" action -->

        <div style="width: 560px;" class="newcomments"><?php
            if (Zend_Auth::getInstance()->hasIdentity()) :
                echo $this->commentsForm;
            else :
    ?>Login to Post comments<?php
                endif;
    ?></div>

<?php $this->inlineScript()->appendFile('/public/js/paginator.js') ?>

                <div id="paged-data-container">
    <?php echo $this->render('posts/view.ajax.phtml') ?>
            </div>


            <p id="pc_reference" class="meta"><a href="#" onclick="$('html, body').animate({scrollTop:0}, 'slow');">Scroll to Top</a></p>

            <div class="pc_panel" id="pc_panel">
                <div class="pc_label expand"></div>
                <div class="pc_label close"></div>
                <div class="pc_title">More on this topic</div>
                <div id="pc_wrapper" class="pc_wrapper">
        <?php
                $model = new Model_DbTable_Posts();
                $morePosts = $model->getMorePostsByMobiler($post["user_id"]);
                foreach ($morePosts as $more):
        ?>

                    <div id="pc_content">
                        <div class="pc_item">
                            <h2><?php print $more["title"]; ?></h2>
                <?php print "<img src='/image/resize?filename=/public/uploads/posts/" . $more["photo"] . "&width=60&height=60' height='80' />"; ?>
                    <p>A slick overlay effect that let's you show notes on a portfolio item</p>
                    <div class="pc_more">http://tympanus.net/codrops/2010/10/12/annotation-overlay-effect/</div>
                </div>

            </div>
        <?php endforeach; ?>
                </div>
                <div id="pc_slider" class="pc_slider"></div>
            </div>

<?php endforeach; ?>

                                <script type="text/javascript">
                                    $(function() {
                                        //window width and height
                                        var window_w 					= $(window).width();
                                        var window_h 					= $(window).height();
                                        //the main panel div
                                        var $pc_panel = $('#pc_panel');
                                        //the wrapper and the content divs
                                        var $pc_wrapper					= $('#pc_wrapper');
                                        var $pc_content					= $('#pc_content');
                                        //the slider / slider div
                                        var $pc_slider					= $('#pc_slider');
                                        //the element reference - reaching this element
                                        //activates the panel
                                        var $pc_reference 				= $('#pc_reference');

                                        var maxWidth,maxHeight,marginL;

                                        buildPanel();

                                        function buildPanel(){
                                            $pc_panel.css({'height': window_h + 'px'});
                                            hidePanel();
                                            //we want to display the items in a grid.
                                            //we need to calculate how much width and height
                                            //the wrapper should have.
                                            //we also want to display it centered, so we need to calculate
                                            //the margin left of the wrapper

                                            //First, lets see how much of height:
                                            //maxHeight = Math.floor((window_h-20)/135)*135;
                                            //20 => pc_titles height
                                            //135 => 125 of each items height plus its margin (10)
                                            maxHeight 		= Math.floor((window_h-20)/135)*135;
                                            //maxWidth = Math.floor((window_w-35)/220)*220;
                                            //220 = item width + margins (left and right)
                                            maxWidth 		= Math.floor((window_w-35)/220)*220;
                                            marginL  		= (window_w - maxWidth)/2;
                                            $pc_wrapper.css({
                                                'width' 		: maxWidth + 20 + 'px',
                                                'height'		: maxHeight +'px',
                                                'margin-left' 	: marginL + 'px'
                                            });

                                            //innitialize the slider
                                            try{
                                                $pc_slider.slider('destroy');
                                            }catch(e){}
                                            //total_scroll is the number of how much we can scroll
                                            var total_scroll = $pc_content.height()-maxHeight;
                                            //add a slider to scroll the content div
                                            //hidden until the panel is expanded
                                            if(total_scroll > 0){
                                                $pc_slider.slider({
                                                    orientation	: 'vertical',
                                                    max			: total_scroll,
                                                    min			: 0,
                                                    value		: total_scroll,
                                                    slide		: function(event, ui) {
                                                        $pc_wrapper.scrollTop(Math.abs(ui.value-total_scroll));
                                                    }
                                                }).css({
                                                    'height'	: maxHeight -40 + 'px',//40 extra
                                                    'left'		: maxWidth + 20 + marginL + 'px',
                                                    'top'		: 30 + 20 + 'px',
                                                    //30 = 20 of title + 10 margin, 20 extra
                                                    'display'	: 'none'
                                                });
                                            }
                                        }

                                        //the panel gets positioned out of the viewport,
                                        //and ready to be slided out!
                                        function hidePanel(){
                                            //165 => 20 pc_title + 120 item + margins
                                            $pc_panel.css({
                                                'right'	: -window_w + 'px',
                                                'top'	: window_h - 165 + 'px'
                                            }).show();
                                            try{
                                                //position the slider in the beginning
                                                slideTop();
                                            }catch(e){}
                                            $pc_slider.hide();
                                            $pc_panel.find('.collapse')
                                            .addClass('expand')
                                            .removeClass('collapse');
                                        }

                                        //resets the slider by sliding it to the top
                                        function slideTop(){
                                            var total_scroll 	= $pc_content.height()-maxHeight;
                                            $pc_wrapper.scrollTop(0);
                                            $pc_slider.slider('option', 'value', total_scroll );
                                        }

                                        $(window).bind('scroll',function(){
                                            /*
                                                    When we reach the element pc_reference, we want to show the panel.
                                                    Let's get the distance from the top to the element
                                             */
                                            var distanceTop = $pc_reference.offset().top - window_h;
                                            if($(window).scrollTop() > distanceTop){
                                                if(parseInt($pc_panel.css('right'),10) == -window_w)
                                                    $pc_panel.stop().animate({'right':'0px'},300);
                                            }
                                            else{
                                                if(parseInt($pc_panel.css('right'),10) == 0)
                                                    $pc_panel.stop().animate({'right': -window_w + 'px'},300,function(){
                                                        hidePanel();
                                                    });
                                            }
                                        }).bind('resize',function(){
                                            //on resize calculate the windows dimentions again,
                                            //and build the panel accordingly
                                            window_w 			= $(window).width();
                                            window_h 			= $(window).height();
                                            buildPanel();
                                        });

                                        //when clicking on the expand button,
                                        //we animate the panel to the size of the window,
                                        //reset the slider and show it
                                        $pc_panel.find('.expand').bind('click',function(){
                                            var $this = $(this);
                                            $pc_wrapper.hide();
                                            $pc_panel.stop().animate({'top':'0px'},500,function(){
                                                $pc_wrapper.show();
                                                slideTop();
                                                $pc_slider.show();
                                                $this.addClass('collapse').removeClass('expand');
                                            });
                                        })

                                        //clicking collapse will hide the slider,
                                        //and minimize the panel
                                        $pc_panel.find('.collapse').live('click',function(){
                                            var $this = $(this);
                                            $pc_wrapper.hide();
                                            $pc_slider.hide();
                                            $pc_panel.stop().animate({'top':window_h - 165 + 'px'},500,function(){
                                                $pc_wrapper.show();
                                                $this.addClass('expand').removeClass('collapse');
                                            });
                                        });

                                        //clicking close will make the panel disappear
                                        $pc_panel.find('.close').bind('click',function(){
                                            $pc_panel.remove();
                                            $(window).unbind('scroll').unbind('resize');
                                        });

                                        //mouse over the items add class "selected"
                                        $pc_wrapper.find('.pc_item').hover(
                                        function(){
                                            $(this).addClass('selected');
                                        },
                                        function(){
                                            $(this).removeClass('selected');
                                        }
                                    ).bind('click',function(){
                                            window.open($(this).find('.pc_more').html());
                                        });
                                    });
                    </script>