<tr>
    <td><input type="checkbox" class="ui-helper-hidden-accessible"><span class="ui-checkbox"></span></td>
    <td><?php print $this->ceg ?></td>
    <td><?php print $this->cim ?></td>
    <td><?php print $this->nev ?></td>
    <td><?php print $this->beosztas ?></td>
    <td><?php print $this->telefon ?></td>
    <td><?php print $this->email ?></td>
    <td><?php print $this->uzenet ?></td>
    <td class="options-width">
<!--        <a href='/user/update/id/<?php echo $this->id; ?>' class="icon-1 info-tooltip"></a>-->
        <!--                                            <a href="" class="icon-3 info-tooltip"></a>
                                                        <a href="" class="icon-4 info-tooltip"></a>-->
        <a onclick="return confirm('Biztos benne?');" href="/kalkulator/index/delete/id/<?php echo $this->id; ?>" class="icon-2 info-tooltip"></a>
    </td>
</tr>                                            