<div id="content">

    <!--  start page-heading -->
    <div id="page-heading">
        <h1>Menüpontok</h1>
    </div>
    <!-- end page-heading -->

    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
        <tbody><tr>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowleft.jpg" width="20" height="300" alt=""></th>
                <th class="topleft"></th>
                <td id="tbl-border-top">&nbsp;</td>
                <th class="topright"></th>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowright.jpg" width="20" height="300" alt=""></th>
            </tr>
            <tr>
                <td id="tbl-border-left"></td>
                <td>
                    <!--  start content-table-inner ...................................................................... START -->
                    <div id="content-table-inner">

                        <!--  start table-content  -->
                        <div id="table-content">
                            <p>Current Menu: <?php echo $this->menu->name; ?></p>
                            <p><a href='/menuitem/add/menu/<?php echo $this->menu->id ?>'>Add a new item</a></p>

                            <!--				<div id="message-yellow">
                                                                                        <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                                                                        <tbody><tr>
                                                                                                <td class="yellow-left">You have a new message. <a href="">Go to Inbox.</a></td>
                                                                                                <td class="yellow-right"><a class="close-yellow"><img src="/public/admin/images/table/icon_close_yellow.gif" alt=""></a></td>
				</tr>
				</tbody></table>
				</div>
				  end message-yellow
                            
				  start message-red
				<div id="message-red">
                                                                                        <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                                                                        <tbody><tr>
                                                                                                <td class="red-left">Error. <a href="">Please try again.</a></td>
                                                                                                <td class="red-right"><a class="close-red"><img src="/public/admin/images/table/icon_close_red.gif" alt=""></a></td>
				</tr>
				</tbody></table>
				</div>
				  end message-red
                            
				  start message-blue
				<div id="message-blue">
                                                                                        <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                                                                        <tbody><tr>
                                                                                                <td class="blue-left">Welcome back. <a href="">View my account.</a> </td>
                                                                                                <td class="blue-right"><a class="close-blue"><img src="/public/admin/images/table/icon_close_blue.gif" alt=""></a></td>
				</tr>
				</tbody></table>
				</div>
				  end message-blue-->

                            <!--				  start message-green-->

                            <?php if ($_GET["deactive_display"] == "1") { ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen inaktiválta hirdetését!</td>
                                                <td class="green-right"><a class="close-green"><img src="/tersege/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            <?php } ?>

                            <?php if ($_GET["active_display"] == "1") { ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen aktiválta hirdetését!</td>
                                                <td class="green-right"><a class="close-green"><img src="/tersege/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            <?php } ?>

                            <?php if ($_GET["create_display"] == "1") { ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen létrehozta hirdetését!</td>
                                                <td class="green-right"><a class="close-green"><img src="/tersege/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            <?php } ?>

                            <?php if ($_GET["delete_display"] == "1") { ?>
                                <div id="message-red">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="red-left">Sikeresen törölte hirdetését!</td>
                                                <td class="red-right"><a class="close-red"><img src="/tersege/public/admin/images/table/icon_close_red.gif" alt=""></a></td>
                                            </tr>
                                        </tbody></table>
                                </div>
                            <?php } ?>

                            <?php if ($_GET["update_display"] == "1") { ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen módosította hirdetését!</td>
                                                <td class="green-right"><a class="close-green"><img src="/tersege/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            <?php } ?>
                            <!--				  end message-green-->


                            <!--  start product-table ..................................................................................... -->
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>
                                            <th class="table-header-check"><a id="toggle-all"></a> </th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Label</a>	</th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Név</a></th>                                            
                                            <th class="table-header-repeat line-left"><a href="">Link</a></th>
                                            <th class="table-header-repeat line-left"><a href="">&nbsp;</a></th>
                                            <th class="table-header-repeat line-left"><a href="">&nbsp;</a></th>
                                            <th class="table-header-options line-left"><a href="">Opciók</a></th>
                                        </tr>
                                        <?php if ($this->items != null) { ?>
                                            <?php echo $this->partialLoop('partials/_menu-item-row.phtml', $this->items); ?>
                                        <?php } else { ?>         
                                            <tr><td colspan="7">You do not have any pages yet.</td></tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>
                        </div>
                        <!--  end content-table  -->

                        <!--  start actions-box ............................................... -->
                        <div id="actions-box">
                            <!--                            <a href="" class="action-slider"></a>
                                                        <div id="actions-box-slider">
                                                            <a href="" class="action-edit">Edit</a>
                                                            <a href="" class="action-delete">Delete</a>
                                                        </div>
                                                        <div class="clear"></div>-->
                        </div>
                        <!-- end actions-box........... -->

                        <!--  start paging..................................................... -->
<!--                        <table border="0" cellpadding="0" cellspacing="0" id="paging-table">
                            <tbody><tr>
                                    <td>
                                        <a href="" class="page-far-left"></a>
                                        <a href="" class="page-left"></a>
                                        <div id="page-info">Page <strong>1</strong> / 15</div>
                                        <a href="" class="page-right"></a>
                                        <a href="" class="page-far-right"></a>
                                    </td>
                                    <td>
                                        <input id="_input" type="text" class="styledselect_pages" autocomplete="off" readonly="" tabindex="0"><div id="_container" class="selectbox-wrapper2" style="display: none; width: 130px; "><ul><li id="_input_" class="selected2">Number of rows</li><li id="_input_">1</li><li id="_input_">2</li><li id="_input_">3</li></ul></div><select class="styledselect_pages" style="display: none; ">
                                            <option value="">Number of rows</option>
                                            <option value="">1</option>
                                            <option value="">2</option>
                                            <option value="">3</option>
                                        </select>
                                    </td>
                                </tr>
                            </tbody></table>-->
                        <!--  end paging................ -->

                        <div class="clear"></div>

                    </div>
                    <!--  end content-table-inner ............................................END  -->
                </td>
                <td id="tbl-border-right"></td>
            </tr>
            <tr>
                <th class="sized bottomleft"></th>
                <td id="tbl-border-bottom">&nbsp;</td>
                <th class="sized bottomright"></th>
            </tr>
        </tbody></table>
    <div class="clear">&nbsp;</div>

</div>