<div id="content">


    <div class="wrapper">
        <div id="sidebar-2" class="right">
            <div class="moduletable-video">
                <h3>
                    <a href="<?php print $this->baseUrl();?>/<?php print $this->locale();?>/user/index/id/<?php print $this->user["user_id"]; ?>">
                        <?php print $this->user["user_username"]; ?>
                    </a>
                </h3>
                <a href="<?php print $this->baseUrl();?>/<?php print $this->locale();?>/user/index/id/<?php print $this->user["user_id"]; ?>"><img class="img-indent border user-view-img"
                     src="<?php print $this->baseUrl(); ?>/public/uploads/users/<?php print $this->user['user_photo']; ?>" alt="" /></a>
            </div>		
            <div class="clear"></div>
            <div class="moduletable-news">
                <h3>Gallery</h3> 
                    <ul id="gallery-images">

                    </ul>                   
            </div>
            <div class="moduletable-perfomance">
                <h3></h3>

            </div>

        </div>


        <div class="blog">






            <div class="items-row cols-1 row-0">
                <div class="item column-1">

                    <h2><?php print $this->gear["gear_name"]; ?></h2>    





                    <dl class="article-info">
                        <?php if ($this->editable == "1") { ?>
                            <a href="<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/gears/edit/id/<?php print $this->gear["gear_id"]; ?>">Edit</a>
                        <?php } ?>
                        <dt class="article-info-term">Details</dt>                        
                        <dd class="category-name">Category: <?php print $this->gear["category"]; ?> - <?php print $this->gear["subcategory"]; ?> - <?php print $this->gear["subsubcategory"]; ?></dd>
                        <dd class="create">Created on <?php print date("Y.m.d.", $this->gear["create_date"]); ?></dd>
                        <dd class="serial-number">Serial number: <?php print $this->gear["serial_number"]; ?></dd>
                        <dd class="hits">
                            Hits: <?php print $this->gear["hits"]; ?>	</dd>
                    </dl>

                    <img class="img-indent border gear-view-img"
                         src="<?php print $this->baseUrl(); ?>/public/uploads/gears/<?php print $this->gear['gear_photo_url']; ?>" alt="" />
                    <p><?php print $this->gear["description"]; ?></p>                    

                    <div class="item-separator"></div>
                </div>
                <span class="row-separator"></span>
            </div>                        
            <div class="items-row cols-1 row-0">
                <div class="item column-1">                        
                    <h2>Comments</h2> 
                        <?php
                            $auth = Zend_Auth::getInstance();
                            if ($auth->hasIdentity()) {
                        ?>            
                            <?php print $this->commentsForm; ?>
                        <?php
                            }
                        ?>
                </div>
            </div>                

            <div class="items-row cols-1 row-0">
                <div class="item column-1">

                    <ul id="comments" class="user-links">

                    </ul>

                </div>
            </div>

        </div>

    </div>
</div>
