<div id="content">

    <div class="wrapper">

        <div class="item-page">
            <h2><?php print $this->gear["gear_name"]; ?></h2>    
            <br />
            <?php if ($this->editable == "1") { ?>
                <a href="<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/gears/edit/id/<?php print $this->gear["gear_id"]; ?>">Edit</a>
            <?php } ?>

            <dl class="article-info">
                <dt class="article-info-term">Details</dt>
                <dd class="category-name">Category: <?php print $this->gear["category"]; ?> - <?php print $this->gear["subcategory"]; ?> - <?php print $this->gear["subsubcategory"]; ?></dd>
                <dd class="create">Created on <?php print date("Y.m.d.", $this->gear["create_date"]); ?></dd>
                <dd class="serial-number">Serial number: <?php print $this->gear["serial_number"]; ?></dd>
                <dd class="hits">
                    Hits: 984	</dd>
            </dl>

            <img class="img-indent border gear-view-img"
                 src="<?php print $this->baseUrl(); ?>/public/uploads/gears/<?php print $this->gear['gear_photo_url']; ?>" alt="" />
            <p><?php print $this->gear["description"]; ?></p>
        </div>
    </div>
</div>
