<div id="content">

<div class="wrapper">

<div class="item-page">
<h2><?php print $this->band[0]["band_name"]; ?></h2>

<dl class="article-info">
	<dt class="article-info-term">Details</dt>
	<dd class="category-name">Style: <?php print $this->band[0]["style"]; ?></dd>
	<dd class="create">Created on <?php print date("Y.m.d.", $this->band[0]["date"]); ?></dd>
</dl>

<img class="img-indent border"
	src="<?php print $this->baseUrl(); ?>/public/timthumb.php?src=<?php print $this->baseUrl(); ?>/public/uploads/bands/<?php print $this->band[0]['band_photo_url']; ?>&h=300&w=400" alt="" />

</div>

</div>

</div>
