<div id="admin-content">

    <!--  start page-heading -->
    <div id="page-heading">
        <h1>Címkék</h1>
    </div>
    <!-- end page-heading -->

    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
        <tbody><tr>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowleft.jpg" width="20" height="300" alt=""></th>
                <th class="topleft"></th>
                <td id="tbl-border-top">&nbsp;</td>
                <th class="topright"></th>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowright.jpg" width="20" height="300" alt=""></th>
            </tr>
            <tr>
                <td id="tbl-border-left"></td>
                <td>
                    <!--  start content-table-inner ...................................................................... START -->
                    <div id="content-table-inner">

                        <!--  start table-content  -->
                        <div id="table-content">

                            <?php if ($_GET["delete"] == "1") { ?>
                                <div id="message-red">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="red-left">Sikeresen törölte a címkét!</td>
                                                <td class="red-right"><a class="close-red"><img src="/public/admin/images/table/icon_close_red.gif" alt=""></a></td>
                                            </tr>
                                        </tbody></table>
                                </div>
                            <?php } ?>
                            <!--				  end message-green-->


                            <!--  start product-table ..................................................................................... -->
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>                                            
                                            <th class="table-header-repeat line-left"><a href="">ID</a></th>
                                            <th class="table-header-repeat line-left"><a href="">Hozzászólás címe</a></th>
                                            <th class="table-header-repeat line-left"><a href="">Címke</a></th>
                                            <th class="table-header-options line-left"><a href="">Opciók</a></th>
                                        </tr>
                                        <?php if ($this->tags != null) { ?>

                                            <?php echo $this->partialLoop('partials/_tag-row.phtml', $this->tags); ?>

                                        <?php } else { ?>
                                            <tr><td colspan="5">Nincs regisztrált felhasználó.</td></tr>
                                        <?php } ?>
                                        
                                            
                                        
                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>
                        </div>
                        <!--  end content-table  -->                       

                        <div class="clear"></div>

                    </div>
                    <!--  end content-table-inner ............................................END  -->
                </td>
                <td id="tbl-border-right"></td>
            </tr>
            <tr>
                <th class="sized bottomleft"></th>
                <td id="tbl-border-bottom">&nbsp;</td>
                <th class="sized bottomright"></th>
            </tr>
        </tbody></table>
    <div class="clear">&nbsp;</div>

</div>