<div id="admin-content">

    <!--  start page-heading -->
    <div id="page-heading">
        <h1>Hozzászólások</h1>
    </div>
    <!-- end page-heading -->

    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
        <tbody><tr>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowleft.jpg" width="20" height="300" alt=""></th>
                <th class="topleft"></th>
                <td id="tbl-border-top">&nbsp;</td>
                <th class="topright"></th>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowright.jpg" width="20" height="300" alt=""></th>
            </tr>
            <tr>
                <td id="tbl-border-left"></td>
                <td>
                    <!--  start content-table-inner ...................................................................... START -->
                    <div id="content-table-inner">

                        <!--  start table-content  -->
                        <div id="table-content">

                            <!--				  start message-green-->

                            <?php if ($_GET["deactive_display"] == "1") {
 ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen inaktiválta a bejegyzést!</td>
                                                <td class="green-right"><a class="close-green"><img src="/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
<?php } ?>

<?php if ($_GET["active_display"] == "1") { ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen aktiválta a bejegyzést!</td>
                                                <td class="green-right"><a class="close-green"><img src="/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
<?php } ?>

<?php if ($_GET["create_display"] == "1") { ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen létrehozta a bejegyzést!</td>
                                                <td class="green-right"><a class="close-green"><img src="/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
<?php } ?>

<?php if ($_GET["delete"] == "1") { ?>
                                <div id="message-red">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="red-left">Sikeresen törölte a hozzászólást!</td>
                                                <td class="red-right"><a class="close-red"><img src="/public/admin/images/table/icon_close_red.gif" alt=""></a></td>
                                            </tr>
                                        </tbody></table>
                                </div>
<?php } ?>

<?php if ($_GET["update_display"] == "1") { ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen módosította a bejegyzést!</td>
                                                <td class="green-right"><a class="close-green"><img src="/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
<?php } ?>
                            <!--				  end message-green-->

<!--                            <link type="text/css" href="/public/css/jquery-ui.css" rel="stylesheet" />
                            <link type="text/css" href="/public/css/ui.multiselect.css" rel="stylesheet" />
                            <script type="text/javascript" src="/public/js/ui.multiselect.js"></script>
                            <script type="text/javascript">
                                $(function(){
                                    $("#receiver").multiselect();
                                    $("#receiver").multiselect({sortable: false, searchable: false});
                                });
                            </script>-->

<?php print $this->form; ?>
                        </div>
                        <!--  end content-table  -->

                        <div class="clear"></div>

                    </div>
                    <!--  end content-table-inner ............................................END  -->
                </td>
                <td id="tbl-border-right"></td>
            </tr>
            <tr>
                <th class="sized bottomleft"></th>
                <td id="tbl-border-bottom">&nbsp;</td>
                <th class="sized bottomright"></th>
            </tr>
        </tbody></table>
    <div class="clear">&nbsp;</div>
</div>