
<div id="admin-content">
    <!--  start page-heading -->
    <div id="page-heading">
        <h1>Bejegyzések</h1>
    </div>
    <!-- end page-heading -->

    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
        <tbody><tr>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowleft.jpg" width="20" height="300" alt=""></th>
                <th class="topleft"></th>
                <td id="tbl-border-top">&nbsp;</td>
                <th class="topright"></th>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowright.jpg" width="20" height="300" alt=""></th>
            </tr>
            <tr>
                <td id="tbl-border-left"></td>
                <td>
                    <!--  start content-table-inner ...................................................................... START -->
                    <div id="content-table-inner">

                        <!--  start table-content  -->
                        <div id="table-content">

                            <!--				  start message-green-->

                            <?php if ($_GET["create"] == "1") { ?>
                                <div id="message-green">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="green-left">Sikeresen elküldte üzenetét!</td>
                                                <td class="green-right"><a class="close-green"><img src="/public/admin/images/table/icon_close_green.gif" alt=""></a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            <?php } ?>

                            <?php if ($_GET["delete"] == "1") { ?>
                                <div id="message-red">
                                    <table border="0" width="100%" cellpadding="0" cellspacing="0">
                                        <tbody><tr>
                                                <td class="red-left">Sikeresen törölte üzenetét!</td>
                                                <td class="red-right"><a class="close-red"><img src="/public/admin/images/table/icon_close_red.gif" alt=""></a></td>
                                            </tr>
                                        </tbody></table>
                                </div>
                            <?php } ?>
                            <!--				  end message-green-->


                            <!--  start product-table ..................................................................................... -->
                            <?php print $this->form; ?>                       
                        </div>
                        <!--  end content-table  -->

                        <!--  start actions-box ............................................... -->
                        <div id="actions-box">
                            <!--                            <a href="" class="action-slider"></a>
                                                        <div id="actions-box-slider">
                                                            <a href="" class="action-edit">Edit</a>
                                                            <a href="" class="action-delete">Delete</a>
                                                        </div>
                                                        <div class="clear"></div>-->
                        </div>
                        <!-- end actions-box........... -->

                        <!--  start paging..................................................... -->
<!--                        <table border="0" cellpadding="0" cellspacing="0" id="paging-table">
                            <tbody><tr>
                                    <td>
                                        <a href="" class="page-far-left"></a>
                                        <a href="" class="page-left"></a>
                                        <div id="page-info">Page <strong>1</strong> / 15</div>
                                        <a href="" class="page-right"></a>
                                        <a href="" class="page-far-right"></a>
                                    </td>
                                    <td>
                                        <input id="_input" type="text" class="styledselect_pages" autocomplete="off" readonly="" tabindex="0"><div id="_container" class="selectbox-wrapper2" style="display: none; width: 130px; "><ul><li id="_input_" class="selected2">Number of rows</li><li id="_input_">1</li><li id="_input_">2</li><li id="_input_">3</li></ul></div><select class="styledselect_pages" style="display: none; ">
                                            <option value="">Number of rows</option>
                                            <option value="">1</option>
                                            <option value="">2</option>
                                            <option value="">3</option>
                                        </select>
                                    </td>
                                </tr>
                            </tbody></table>-->
                        <!--  end paging................ -->

                        <div class="clear"></div>

                    </div>
                    <!--  end content-table-inner ............................................END  -->
                </td>
                <td id="tbl-border-right"></td>
            </tr>
            <tr>
                <th class="sized bottomleft"></th>
                <td id="tbl-border-bottom">&nbsp;</td>
                <th class="sized bottomright"></th>
            </tr>
        </tbody></table>
    <div class="clear">&nbsp;</div>

</div>