<div id="sidebar-2" class="right">

	<div class="moduletable">
		<h3>
			<cufon class="cufon cufon-canvas" alt="Login "
				style="width: 82px; height: 27px; ">
			<canvas width="101" height="29"
				style="width: 101px; height: 29px; top: -1px; left: 0px; "></canvas>
			<cufontext>Login </cufontext></cufon>
			<cufon class="cufon cufon-canvas" alt="Form"
				style="width: 73px; height: 27px; ">
			<canvas width="78" height="29"
				style="width: 78px; height: 29px; top: -1px; left: 0px; "></canvas>
			<cufontext>Form</cufontext></cufon>
		</h3>
		<form action="/joomla_34465/index.php" method="post" id="login-form">

			<div class="box-indent">

				<fieldset class="userdata">

					<p id="form-login-username">

						<input id="modlgn-username" type="text" name="username"
							class="inputbox" size="18">

					</p>

					<p id="form-login-password">

						<input id="modlgn-passwd" type="password" name="password"
							class="inputbox" size="18">

					</p>

					<div class="wrapper">
						<p id="form-login-remember">

							<input id="modlgn-remember" type="checkbox" name="remember"
								class="checkbox" value="yes"> <label for="modlgn-remember">Remember
								Me</label>

						</p>

						<a class="button-login" href="#"
							onclick="document.getElementById('login-form').submit()"><cufon
								class="cufon cufon-canvas" alt="Login"
								style="width: 76px; height: 28px; ">
							<canvas width="88" height="30"
								style="width: 88px; height: 30px; top: -1px; left: 0px; "></canvas>
							<cufontext>Login</cufontext></cufon>
						</a>
					</div>

					<input type="hidden" name="option" value="com_users"> <input
						type="hidden" name="task" value="user.login"> <input type="hidden"
						name="return" value="aW5kZXgucGhwP0l0ZW1pZD00NjQ="> <input
						type="hidden" name="1265dcf83913594a045c7a245b6dd914" value="1">
				</fieldset>

			</div>

			<ul class="user-links">

				<li><a
					href="/joomla_34465/index.php/using-joomla/extensions/components/users-component/password-reset">

						Forgot your password?</a></li>

				<li><a
					href="/joomla_34465/index.php/using-joomla/extensions/components/users-component/registration-form">

						Create an account</a></li>

			</ul>

		</form>

	</div>
	
	<div class="moduletable-news">
		<h3>
			<cufon class="cufon cufon-canvas" alt="most "
				style="width: 81px; height: 27px; ">
			<canvas width="100" height="29"
				style="width: 100px; height: 29px; top: -1px; left: 0px; "></canvas>
			<cufontext>most </cufontext></cufon>
			<cufon class="cufon cufon-canvas" alt="popular "
				style="width: 122px; height: 27px; ">
			<canvas width="141" height="29"
				style="width: 141px; height: 29px; top: -1px; left: 0px; "></canvas>
			<cufontext>popular </cufontext></cufon>
			<cufon class="cufon cufon-canvas" alt="lyrics"
				style="width: 84px; height: 27px; ">
			<canvas width="96" height="29"
				style="width: 96px; height: 29px; top: -1px; left: 0px; "></canvas>
			<cufontext>lyrics</cufontext></cufon>
		</h3>

		<!-- START 'DisplayNews by BK 2.0RC1' -->

		<div class="-news ">
			<ul class="scroller" style="top: -28px;">
				<li class="item-news"><span class="contentheading-news "><a
						href="/joomla_34465/index.php/80-news-lyrics/87-1"
						class="contentpagetitle-news ">Nicki Minaj</a> </span> <span>"Moment
						4 Life"</span>
					<div style="clear: both;"></div>
				</li>
				<li class="item-news"><span class="contentheading-news "><a
						href="/joomla_34465/index.php/80-news-lyrics/89-3"
						class="contentpagetitle-news ">My Chemical Romance</a> </span> <span>"SING"</span>
					<div style="clear: both;"></div>
				</li>
				<li class="item-news"><span class="contentheading-news "><a
						href="/joomla_34465/index.php/80-news-lyrics/114-britney-spears"
						class="contentpagetitle-news ">Britney Spears</a> </span> <span>"Hold
						It Against Me"</span>
					<div style="clear: both;"></div>
				</li>
				<li class="item-news"><span class="contentheading-news "><a
						href="/joomla_34465/index.php/80-news-lyrics/88-2"
						class="contentpagetitle-news ">Warpaint</a> </span> <span>"Undertow"</span>
					<div style="clear: both;"></div>
				</li>
				<li class="item-news"><span class="contentheading-news "><a
						href="/joomla_34465/index.php/80-news-lyrics/90-4"
						class="contentpagetitle-news ">B.o.B </a> </span> <span>"Don't Let
						Me Fall"</span>
					<div style="clear: both;"></div>
				</li>
				<li class="item-news"><span class="contentheading-news "><a
						href="/joomla_34465/index.php/80-news-lyrics/112-kimberly-caldwell"
						class="contentpagetitle-news ">Kimberly Caldwell</a> </span> <span>"Desperate
						Girls"</span>
					<div style="clear: both;"></div>
				</li>
				<li class="item-news"><span class="contentheading-news "><a
						href="/joomla_34465/index.php/80-news-lyrics/115-martin-solveig"
						class="contentpagetitle-news ">Martin Solveig</a> </span> <span>"Hello"</span>
					<div style="clear: both;"></div>
				</li>
				<li class="item-news"><span class="contentheading-news "><a
						href="/joomla_34465/index.php/80-news-lyrics/113-katy-perry"
						class="contentpagetitle-news ">Katy Perry</a> </span> <span>"Teenage
						Dream"</span>
					<div style="clear: both;"></div>
				</li>
			</ul>
		</div>

		<!-- END 'DisplayNews by BK 2.0RC1' -->
		<div class="buttons">
			<a class="next" href="#"></a><a class="prev" href="#"></a>
		</div>
	</div>
	<div class="moduletable-perfomance">
		<h3>
			<cufon class="cufon cufon-canvas" alt="Live "
				style="width: 61px; height: 27px; ">
			<canvas width="81" height="29"
				style="width: 81px; height: 29px; top: -1px; left: 0px; "></canvas>
			<cufontext>Live </cufontext></cufon>
			<cufon class="cufon cufon-canvas" alt="Performance"
				style="width: 186px; height: 27px; ">
			<canvas width="199" height="29"
				style="width: 199px; height: 29px; top: -1px; left: 0px; "></canvas>
			<cufontext>Performance</cufontext></cufon>
		</h3>

		<!-- START 'DisplayNews by BK 2.0RC1' -->

		<span class="-perfomance "><div
				class="item contentpaneopen-perfomance ">
				<span class="contentheading-perfomance "><a
					href="/joomla_34465/index.php/86-live-performance/116-warpaint-live"
					class="contentpagetitle-perfomance ">Warpaint</a> </span><br> <span
					class="text"><img
					src="/joomla_34465/images/stories/live-perfomance-3.jpg" alt=""
					align="left">"Set Your Arms Down (Live)"</span>
				<div style="clear: both;"></div>
			</div>
			<div class="item contentpaneopen-perfomance ">
				<span class="contentheading-perfomance "><a
					href="/joomla_34465/index.php/86-live-performance/119-panic-at-the-disco"
					class="contentpagetitle-perfomance ">Panic! At The Disco</a> </span><br>
				<span class="text"><img
					src="/joomla_34465/images/stories/live-perfomance-4.jpg" alt=""
					align="left">"The Ballad of Mona Lisa (Live)"</span>
				<div style="clear: both;"></div>
			</div>
			<div class="item contentpaneopen-perfomance ">
				<span class="contentheading-perfomance "><a
					href="/joomla_34465/index.php/86-live-performance/117-two-door-cinema-club"
					class="contentpagetitle-perfomance ">Two Door Cinema Club</a> </span><br>
				<span class="text"><img
					src="/joomla_34465/images/stories/live-perfomance-2.jpg" alt=""
					align="left">"Undercover Martyn"</span>
				<div style="clear: both;"></div>
			</div> </span>

		<!-- END 'DisplayNews by BK 2.0RC1' -->
	</div>
</div>
