<div id="sidebar-2" class="right">
    <?php 
        $auth = Zend_Auth::getInstance();
        if(!$auth->hasIdentity()) {
    ?>
	<div class="moduletable">
		<h3>Login Form</h3>
		<form action="<?php print $this->baseUrl(); ?>/<?php print $this->locale(); ?>/user/login" method="post" id="login-form">
			<div class="box-indent">
				<fieldset class="userdata">
					<p id="form-login-username">
						<input id="modlgn-username" type="text" name="username"
							class="inputbox" size="18">
					</p>
					<p id="form-login-password">
						<input id="modlgn-passwd" type="password" name="password"
							class="inputbox" size="18">
					</p>
					<div class="wrapper">
						<p id="form-login-remember">
							<input id="modlgn-remember" type="checkbox" name="remember" class="checkbox" value="yes"> 
							<label for="modlgn-remember">Remember Me</label>
						</p>
						<a class="button-login"
							onclick="document.getElementById('login-form').submit()">Login
						</a>
					</div>
					<input type="hidden" name="option" value="com_users"> 
					<input type="hidden" name="task" value="user.login"> 
					<input type="hidden" name="return" value="aW5kZXgucGhwP0l0ZW1pZD00NjQ="> 
					<input type="hidden" name="1265dcf83913594a045c7a245b6dd914" value="1">
				</fieldset>
			</div>

			<ul class="user-links">

				<li><a
					href="<?php print $this->baseUrl(); ?>/<?php print $this->locale(); ?>/user/password">

						Forgot your password?</a></li>

				<li><a
					href="<?php print $this->baseUrl(); ?>/<?php print $this->locale(); ?>/user/register">

						Create an account</a></li>

			</ul>

		</form>

	</div>
	<?php 
        }
        ?>
	<div class="moduletable-news">
		<h3>
			most popular gears
		</h3>

		<!-- START 'DisplayNews by BK 2.0RC1' -->

		<div class="-news ">
			<ul class='scroller'>
						<li class='item-news'><span class='contentheading-news '><a
								href="#"
								class='contentpagetitle-news '>Ibanez S Prestige</a> </span> 
								<span>John Doe - John Doe Band</span>
							<div style="clear: both;"></div></li>
						<li class='item-news'><span class='contentheading-news '><a
								href="#"
								class='contentpagetitle-news '>ESP Stephen Carpenter Signature</a> </span>
								<span>John Doe - John Doe Band</span>
							<div style="clear: both;"></div></li>
						<li class='item-news'><span class='contentheading-news '><a
								href="#"
								class='contentpagetitle-news '>Schecter Hellraiser</a> </span> 
								<span>John Doe - John Doe Band</span>
							<div style="clear: both;"></div></li>
						<li class='item-news'><span class='contentheading-news '><a
								href="#"
								class='contentpagetitle-news '>B.C. Rich Zoltan Assasin Maple</a> </span>
								 <span>John Doe - John Doe Band</span>
							<div style="clear: both;"></div></li>
						<li class='item-news'><span class='contentheading-news '><a
								href="#"
								class='contentpagetitle-news '>Ibanez BTB205 TYF</a> </span> 
								<span>John Doe - John Doe Band</span>
							<div style="clear: both;"></div></li>
						<li class='item-news'><span class='contentheading-news '><a
								href="#"
								class='contentpagetitle-news '>Drumcraft DC8</a> </span> 
								<span>John Doe - John Doe Band</span>
							<div style="clear: both;"></div></li>
						<li class='item-news'><span class='contentheading-news '><a
								href="#"
								class='contentpagetitle-news '>Tama Starclassic Bubinga</a> </span>
								<span>John Doe - John Doe Band</span>
							<div style="clear: both;"></div></li>
						<li class='item-news'><span class='contentheading-news '><a
								href="/joomla_34465/index.php/80-news-lyrics/113-katy-perry"
								class='contentpagetitle-news '>Fender Jazz Bass</a> </span> 
								<span>John Doe - John Doe Band</span>
							<div style="clear: both;"></div></li>
					</ul>
		</div>

		<!-- END 'DisplayNews by BK 2.0RC1' -->
		<div class="buttons">
			<a class="next" href="#"></a><a class="prev" href="#"></a>
		</div>
	</div>	
</div>
