<noscript>A böngésződön nincs bekapcsolva a Javascript! Enélkül sajnos nem működik rendesen az oldal.</noscript>
<!--<script language="javascript" type="text/javascript">
    function textCounter( field, countfield, maxlimit ) {
        if ( field.value.length > maxlimit )
        {
            field.value = field.value.substring( 0, maxlimit );            
            return false;
        }
        else
        {
            var kar = document.getElementById('char');
            kar.innerHTML = maxlimit - field.value.length;
        }
    }

    (function($){
        $.fn.extend({
            customStyle : function(options) {
                if(!$.browser.msie || ($.browser.msie&&$.browser.version>6)){
                    return this.each(function() {
                        var currentSelected = $(this).find(':selected');
                        $(this).after('<span class="customStyleSelectBox"><span class="customStyleSelectBoxInner">'+currentSelected.text()+'</span></span>').css({position:'absolute', opacity:0,fontSize:$(this).next().css('font-size')});
                        var selectBoxSpan = $(this).next();
                        var selectBoxWidth = parseInt($(this).width()) - parseInt(selectBoxSpan.css('padding-left')) -parseInt(selectBoxSpan.css('padding-right'));
                        var selectBoxSpanInner = selectBoxSpan.find(':first-child');
                        selectBoxSpan.css({display:'inline-block'});
                        selectBoxSpanInner.css({width:selectBoxWidth-100, display:'inline-block'});
                        var selectBoxHeight = parseInt(selectBoxSpan.height()) + parseInt(selectBoxSpan.css('padding-top')) + parseInt(selectBoxSpan.css('padding-bottom'));
                        $(this).height(selectBoxHeight).change(function(){
                            // selectBoxSpanInner.text($(this).val()).parent().addClass('changed');   This was not ideal
                            selectBoxSpanInner.text($(this).find(':selected').text()).parent().addClass('changed');
                        });
                    });
                }
            }
        });
    })(jQuery);

    $(document).ready(function(){
        $('#sex').customStyle();
        $('#activate').customStyle();
        $('#facebook').customStyle();
        $('#facebook_users').customStyle();
        $('#twitter').customStyle();
        $('#twitter_users').customStyle();
        $('#blog').customStyle();
    });

</script>-->
<form id="form" name="form" action="" method="post">
    <fieldset class="step">
        <div class="rightCol">            
            <div class="formRow"><label>Név *</label></div>
            <div class="formRow"><?php print $this->element->name; ?></div>
            <div class="formRow">
                <label for="username">Nem*</label>
            </div>
            <div class="formRow"><?php print $this->element->sex; ?></div>
            <div class="formRow"><label for="username">Lakhely /város/ *</label></div>
            <div class="formRow"><?php print $this->element->city; ?></div>
            <div class="formRow"><label for="phone">Kor *</label></div>
            <div class="formRow"><?php print $this->element->age; ?></div>
        </div>
    </fieldset>
    <fieldset class="step">
        <div class="rightCol">  
            <div class="formRow"><label for="phone">E-mail cím *</label></div>
            <div class="formRow"><?php print $this->element->email; ?></div>
            <div class="formRow"><label for="phone">Telefon *</label></div>
            <div class="formRow"><?php print $this->element->phone; ?></div>
            <div class="formRow"><label for="phone">Végzettség *</label></div>
            <div class="formRow"><?php print $this->element->graduate; ?></div>
            <div class="formRow"><label for="activate">Az alábbiak közül mivel foglalkozol *</label></div>
            <div class="formRow"><?php print $this->element->activate; ?></div>
        </div>
    </fieldset>
    <fieldset class="step">
        <div class="rightCol">
            <div class="formRow"><label for="phone">Foglalkozás *</label></div>
            <div class="formRow"><?php print $this->element->job; ?></div>
            <div class="formRow"><label for="facebook">Fent vagy Facebookon? *</label></div>
            <div class="formRow"><?php print $this->element->facebook; ?></div>
            <div class="formRow"><label for="facebookUser">Hány ismerősöd van?</label></div>
            <div class="formRow"><?php print $this->element->facebook_users; ?></div>
        </div>
    </fieldset>
    <fieldset class="step">

        <div class="rightCol">
            <div class="formRow" id="twitterBox"><label for="twitter">Fent vagy Twitteren? *</label></div>
            <div class="formRow"><?php print $this->element->twitter; ?></div>
            <div class="formRow"><label for="twitter">Hány követőd van?</label></div>
            <div class="formRow"><?php print $this->element->twitter_users; ?></div>
            <div class="formRow"><label for="blog">Van saját blogod? *</label></div>
            <div class="formRow"><?php print $this->element->blog; ?></div>
            <div class="formRow"><label for="blog_address">Blogod címe</label></div>
            <div class="formRow"><?php print $this->element->blog_address; ?></div>
        </div>
    </fieldset>
    <fieldset class="step">

        <div class="rightCol">
            <div class="formRow"><label for="blog_address">Kedvenc applikációd neve</label></div>
            <div class="formRow"><?php print $this->element->app; ?></div>
            <div class="formRow">
                <label for="bio">Írj magadról 160 karakterben! *
<!--                    <span class="note">(Írd le, milyen vagy! Írd le, milyennek tartanak Téged mások! Írd le, mit gondolsz a világról Írd le, miért lennél Te ideális Mob!ler! Olyat írj, amiből kiderül az egyéniséged és az írásbeli kommunikációs készséged.)</span>-->
                </label>
            </div>
            <div class="formRowTxtArea">
            <?php print $this->element->bio; ?>
            </div>
        </div>
    </fieldset>
    <fieldset class="step" id="lastStep">

        <div class="rightCol">
            <p align="justify">A Samsung Mob!lers 2011-es kampányra (a továbbiakban: Kampány) történő jelentkezés automatikusan nem vonja maga után a kampányban történő részvételt is.
                -	A jelentkezők közül azon résztvevőket, akikkel a Samsung Electronics Magyar Zrt. (a továbbiakban: Samsung) és a lebonyolítást végző Ügynökség (a továbbiakban: Ügynökség) a Kampány során együttműködni kíván, egy a Samsung és Ügynökség munkatársaiból ezen célból létrejövő grémium választja ki. A kiválasztás a jelentkező által kitöltött online adatlapon megadott válaszok és adatok alapján történik.

                -	A kiválasztott személy (a továbbiakban: Mobiler) vállalja, hogy a Kampány során Samsunggal és Ügynökséggel együttműködik a Kampány sikeres lebonyolítása érdekében. Vállalja, hogy egy Együttműködési Nyilatkozat aláírásával bizonyos aktivitásokat elvégez a Kampány során.


                -	A Mobiler együttműködése nem eredményez foglalkoztatásra, munkavégzésre irányuló tevékenységet, annak nem minősül. A Mobiler az együttműködésért anyagi juttatásra nem tart igényt, azt nem kap.
            </p>           
            <p id="terms"><?php print $this->element->terms; ?> <span>Elfogadom a szabályzatot </span></p>

            <button id="regisztracio" type="submit" style="margin-top: 65px;">Regisztrálok</button>

        </div>
    </fieldset>
</form>

