<div id="content-landing" class="content">
<h2><span class="yellow">Köszönjük, hogy jelentkeztél Mob!lernek!</span></h2>
<p class="main">Amennyiben a megadott információk alapján megtetszel nekünk, egy személyes meghallgatásra invitálunk majd, ahol személyesen is bemutatkozhatsz a Samsung Mob!ler Zsűrinek. </p>
<p class="main">Ha választásunk nem Rád esik, ne csüggedj: legközelebb újra nekiveselkedhetsz a megmérettetésnek! Addig pedig kövesd a Mob!lereket a mobilers.samsung.hu oldalon valamint a közösségi portálokon, és tudj meg minél többet a Samsung Mobile izgalmas világáról.</p>
</div>

<!-- (C)2000-2011 Gemius SA - gemiusTraffic / ver 11.1 / sikeres_mobiler -->
<script type="text/javascript">
<!--//--><![CDATA[//><!--
var gemius_identifier = new String('p4OV73MnLbPK1fBphw_hTreP7FjwMXhN9U.b43oEHET.x7');
//--><!]]>
</script>
<script type="text/javascript" src="http://my.samsung.hu/public/js/gemius.js"></script>
