<?php $paginationControl = $this->paginationControl($this->paginator, 'All', 'partials/_pagination-control.phtml', array('gear_id' => $this->gear_id)) ?>

<div class="pagination-control">
    <?php echo $paginationControl ?>
</div>

<div class="paged-data">
    <?php if (count($this->paginator)) : 
            foreach ($this->paginator as $comment) :
    ?>
    <li>
                <?php echo $this->escape($comment["description"]); ?>
    </li>
            <?php endforeach ?>        
    <?php else : ?>
    <p class="notice">No items found</p>
    <?php endif ?>
</div>

<div class="pagination-control">
    <?php echo $paginationControl ?>
</div>