<table class="adminlist" border="0" width="100%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr >
            <th class="title">Bejegyzés címe</th>
            <th>Dátum</th>
            <th>Komment</th>
            <th>&nbsp;</th>
        </tr>
        <?php foreach ($this->comments as $p) {
        ?>
            <tr align="center">
                <td class="title"><?php print $p["title"]; ?></td>
                <td><?php print $p["date"]; ?></td>
                <td><?php print $p["description"]; ?></td>
                <td class="options-width">
                    <a onclick="return confirm('Biztos vagy benne?');" href="<?php print $this->url(array('controller' => 'comments', 'action' => 'delete', 'id' => $p["comment_id"])); ?>">Törlés</a>
            </tr>
        <?php } ?>
    </tbody>
</table>