<div class="wrapper border-2 p3">                        

                    <div class="wrapper border-2 bot-pad margin-bot">

                        <div class="alpha grid_11 suffix_1">

                            <h3 class="indent-bot2">Videók</h3>

                            <div class="wrapper">

                                <div class="alpha grid_5 suffix_1">

                                    <figure class="p3"><iframe width="279" height="171" src="http://www.youtube.com/embed/wcd_wZOcPo4" frameborder="0" allowfullscreen></iframe></figure>

                                    <p class="indent-bot"><a href="#">Lalesua kertase mertyuade</a> ioner grda anasera lorem suaskaéáõúûóüöse agned laorem leot tellus dolobus eget kelementum vel, cursusleifend elitenean auctor wisi et urnaliquam erat volutpat. </p>

                                    <a class="link-1" href="#">Tovább</a>

                                </div>

                                <div class="grid_5 omega">

                                    <figure class="p3"><iframe width="279" height="171" src="http://www.youtube.com/embed/gB6bPni1NBo" frameborder="0" allowfullscreen></iframe></figure>

                                    <p class="indent-bot"><a href="#">Lalesua kertase mertyuade</a> ioner grda anasera lorem suaskase agned laorem leot tellus dolobus eget kelementum vel, cursusleifend elitenean auctor wisi et urnaliquam erat volutpat. </p>

                                    <a class="link-1" href="#">Tovább</a>

                                </div>

                            </div>
                            
                            <div class="wrapper">

                                <div class="alpha grid_5 suffix_1">

                                    <figure class="p3"><iframe width="279" height="171" src="http://www.youtube.com/embed/gB6bPni1NBo" frameborder="0" allowfullscreen></iframe></figure>

                                    <p class="indent-bot"><a href="#">Lalesua kertase mertyuade</a> ioner grda anasera lorem suaskaéáõúûóüöse agned laorem leot tellus dolobus eget kelementum vel, cursusleifend elitenean auctor wisi et urnaliquam erat volutpat. </p>

                                    <a class="link-1" href="#">Tovább</a>

                                </div>

                                <div class="grid_5 omega">

                                    <figure class="p3"><iframe width="279" height="171" src="http://www.youtube.com/embed/wcd_wZOcPo4" frameborder="0" allowfullscreen></iframe></figure>

                                    <p class="indent-bot"><a href="#">Lalesua kertase mertyuade</a> ioner grda anasera lorem suaskase agned laorem leot tellus dolobus eget kelementum vel, cursusleifend elitenean auctor wisi et urnaliquam erat volutpat. </p>

                                    <a class="link-1" href="#">Tovább</a>

                                </div>

                            </div>

                        </div>

                        <div class="grid_4 omega">

                            <h3 class="p2">Popular Info</h3>

                            <ul class="list-1">

                                <li><a href="#">Calculator</a></li>

                                <li><a href="#">Special Offers</a></li>

                                <li><a href="#">Popular Services</a></li>

                                <li><a href="#">Online Consultations</a></li>

                                <li><a href="#">Customer Support</a></li>

                                <li><a href="#">Guarantee</a></li>

                                <li><a href="#">Our Staff</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="wrapper">
                        <div class="alpha grid_6">
                            <div class="indent-top2">
                                <div class="wrapper">
                                    <figure class="fleft"><img src="/public/skins/prym/images/ico1.png" alt="" /></figure>
                                    <div class="extra-wrap">
                                        <div class="indent-r">
                                            <div class="border-3">
                                                <div class="indent">
                                                    <h6>Find Us</h6>
                                                    <a class="link-2" href="#">Search Now!</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="wrapper">
                                    <figure class="fleft"><img src="/public/skins/prym/images/ico2.png" alt="" /></figure>
                                    <div class="extra-wrap">
                                        <div class="indent-r">
                                            <div class="border-3">
                                                <div class="indent">
                                                    <h6>Useful Info</h6>
                                                    <a class="link-2" href="#">Read More</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="wrapper">
                                    <figure class="fleft"><img src="/public/skins/prym/images/ico3.png" alt="" /></figure>
                                    <div class="extra-wrap">
                                        <div class="indent-r">
                                            <div class="indent">
                                                <h6>Price List</h6>
                                                <a class="link-2" href="#">View All</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="grid_3 suffix_1">
                            <h3 class="p3">Links</h3>
                            <ul class="list-2">
                                <li><a href="#">Mibulum molestie</a></li>
                                <li><a href="#">Nasacueno mera umertasa</a></li>
                                <li><a href="#">Badndrerit mauris</a></li>
                                <li><a href="#">Ketyade asellus mertya</a></li>
                                <li><a href="#">Porta musce</a></li>
                            </ul>
                        </div>

                        <div class="grid_6 omega">
                            <h3 class="margin-bot">Quick Message</h3>
                            <form name="quick" id="quick-form">
                                <label class="label-1">
                                    <input class="quicktext" name="keyword" type="text" value="Your E-Mail:"  onBlur="if(this.value=='') this.value='Your E-Mail:'" onFocus="if(this.value =='Your E-Mail:' ) this.value=''" />
                                </label>
                                <label class="label-2">
                                    <textarea class="quickmessage" onBlur="if(this.value=='') this.value='Message:'" onFocus="if(this.value =='Message:' ) this.value=''">Message:</textarea>
                                </label>
                                <div class="alignright indent-r">
                                    <span class="button2"><a href="#" onClick="document.getElementById('quick-form').submit()">Send</a></span>
                                </div>
                            </form>
                        </div>
                    </div>