<div id="admin-content">
    <!--  start page-heading -->
    <div id="page-heading">
        <h1>Bejegyzések</h1>
    </div>
    <!-- end page-heading -->

    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
        <tbody><tr>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowleft.jpg" width="20" height="300" alt=""></th>
                <th class="topleft"></th>
                <td id="tbl-border-top">&nbsp;</td>
                <th class="topright"></th>
                <th rowspan="3" class="sized"><img src="/public/admin/images/shared/side_shadowright.jpg" width="20" height="300" alt=""></th>
            </tr>
            <tr>
                <td id="tbl-border-left"></td>
                <td>
                    <!--  start content-table-inner ...................................................................... START -->
                    <div id="content-table-inner">

                        <!--  start table-content  -->
                        <div id="table-content">
                            <!--  start product-table ..................................................................................... -->
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>
                                            <th class="table-header-check"> </th>
                                            <th width="775" class="table-header-repeat line-left minwidth-1"><a href="">Összes Mob!ler posztjainak száma </a></th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Adat</a></th>
                                        </tr>
                                        <?php foreach ($this->mostMobilerPost as $post): ?>
                                        <tr>
                                            <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->user_id ?></td>
                                            <td width="775"><?php print $post["username"] ?></td>
                                            <td><?php print $post["COUNT(posts.user_id)"] ?></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>
                                            <th class="table-header-check"> </th>
                                            <th width="775" class="table-header-repeat line-left minwidth-1"><a href="">Legtöbb szavazatot kapott cikk </a></th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Adat</a></th>
                                        </tr>
                                        <?php foreach ($this->mostRatedPost as $post): ?>
                                        <tr>
                                            <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->user_id ?></td>
                                            <td width="775"><?php print $post["title"] ?></td>
                                            <td><?php print $post["rates"] ?></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>
                                            <th class="table-header-check"> </th>
                                            <th width="775" class="table-header-repeat line-left minwidth-1"><a href="">Legtöbb kommentet kapott cikk </a></th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Adat</a></th>
                                        </tr>
                                        <?php foreach ($this->mostCommentedPost as $post): ?>
                                        <tr>
                                            <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->user_id ?></td>
                                            <td width="775"><?php print $post["title"] ?></td>
                                            <td><?php print $post["comments"] ?></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>
                                            <th class="table-header-check"> </th>
                                            <th width="775" class="table-header-repeat line-left minwidth-1"><a href="">Legtöbb szavazatot kapott Mob!ler </a></th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Adat</a></th>
                                        </tr>
                                        <?php foreach ($this->mostRatedMobiler as $post): ?>
                                        <tr>
                                            <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->user_id ?></td>
                                            <td width="775"><?php print $post["username"] ?></td>
                                            <td><?php print $post["COUNT(rates.user_id)"] ?></td>
                                        </tr>
                                        <?php endforeach; ?>

                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>
                                            <th class="table-header-check"> </th>
                                            <th width="775" class="table-header-repeat line-left minwidth-1"><a href="">Legtöbb hozzászólást kapott Mob!ler </a></th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Adat</a></th>
                                        </tr>
                                        <?php foreach ($this->mostCommentedMobiler as $post): ?>
                                        <tr>
                                            <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->user_id ?></td>
                                            <td width="775"><?php print $post["username"] ?></td>
                                            <td><?php print $post["COUNT(comments.user_id)"] ?></td>
                                        </tr>
                                        <?php endforeach; ?>

                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>
                                            <th class="table-header-check"> </th>
                                            <th width="775" class="table-header-repeat line-left minwidth-1"><a href="">Legtöbb hozzászólást beküldő felhasználó</a></th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Adat</a></th>
                                        </tr>
                                        <?php foreach ($this->mostUserComments as $post): ?>
                                        <tr>
                                            <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->user_id ?></td>
                                            <td width="775"><?php print $post["username"] ?></td>
                                            <td><?php print $post["COUNT(comments.user_id)"] ?></td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>
                            <form id="mainform" action="">
                                <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
                                    <tbody>
                                        <tr>
                                            <th class="table-header-check"> </th>
                                            <th width="775" class="table-header-repeat line-left minwidth-1"><a href="">Legtöbb szavazatot adó felhasználó </a></th>
                                            <th class="table-header-repeat line-left minwidth-1"><a href="">Adat</a></th>
                                        </tr>
                                        <?php foreach ($this->mostUserRate as $post): ?>
                                        <tr>
                                            <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->user_id ?></td>
                                            <td width="775"><?php print $post["username"] ?></td>
                                            <td><?php print $post["COUNT(rates.user_id)"] ?></td>
                                        </tr>
                                        <?php endforeach; ?>

                                    </tbody>
                                </table>
                                <!--  end product-table................................... -->
                            </form>






                        </div>
                        <!--  end content-table  -->

                        <!--  start actions-box ............................................... -->
                        <div id="actions-box">

                        </div>
                        <!-- end actions-box........... -->

                        <div class="clear"></div>

                    </div>
                    <!--  end content-table-inner ............................................END  -->
                </td>
                <td id="tbl-border-right"></td>
            </tr>
            <tr>
                <th class="sized bottomleft"></th>
                <td id="tbl-border-bottom">&nbsp;</td>
                <th class="sized bottomright"></th>
            </tr>
        </tbody></table>
    <div class="clear">&nbsp;</div>

</div>
