<form enctype="multipart/form-data" action="" method="POST">
    <dl>
        <dt>Jelenlegi profilkép:</dt>
        <dd>
            <?php print $this->element->photo_preview; ?>
        </dd>
        <dd>
            <?php print $this->element->photo; ?>
        </dd>	
        <dd>
            <?php print $this->element->description; ?>
        </dd>
        <div>
            <button type="submit" class="button">Save</button>
        </div>
    </dl>
</form>
