<div id="content">
	<div class="wrapper">
		<div class="registration">
			<link
				href="<?php print $this->baseUrl(); ?>/public/skins/gearoscope/css/jquery.autocomplete.css"
				media="screen" rel="stylesheet" type="text/css" />
			<script type="text/javascript"
				src="<?php print $this->baseUrl(); ?>/public/skins/gearoscope/js/jquery.fcbkcomplete.js"></script>
			
	<?php print $this->form; ?>
	<form>    
</form>
		</div>
	</div>
</div>
