<form id="member-registration"
	action="<?php print $this->baseUrl(); ?>/<?php print $this->locale(); ?>/user/newpassword" method="post"
	class="form-validate">
	<fieldset>
		<legend>Jelszómódosítás</legend>
		<dl>
			<dt>
				<span class="spacer"><span class="before"></span><span class="text"><label
						id="jform_spacer-lbl" class=""><strong class="red">*</strong>
							Required field</label> </span><span class="after"></span> </span>
			</dt>
			<dd></dd>
			<dt>
				<label id="jform_name-lbl" for="jform_name" class="hasTip required"
					title="Name::Enter your full name">Új jelszó:<span class="star">&#160;*</span>
				</label>
			</dt>
			<dd>
				<!-- <input type="text" name="jform[name]" id="jform_name" value=""
					class="required" size="30" />-->
					<?php print $this->element->password_reg; ?> 
			</dd>
			<dt>
				<label id="jform_username-lbl" for="jform_username"
					class="hasTip required"
					title="Username::Enter your desired user name">Új jelszó mégegyszer:<span
					class="star">&#160;*</span> </label>
			</dt>
			<dd>
				<!-- <input type="text" name="jform[username]" id="jform_username"
					value="" class="validate-username required" size="30" /> -->
					<?php print $this->element->password_reg_confirm; ?> 
			</dd>			
		</dl>
	</fieldset>
	<div>
		<button type="submit" class="validate">Save</button>
		 <input type="hidden" name="option" value="com_users" /> 
		 <input type="hidden" name="task" value="registration.register" /> 
		 <input type="hidden" name="12db47ca459f15d82ed7f4f7ee1d866d" value="1" />
	</div>
</form>
