<div id="content">
	<div class="wrapper">
                <?php if($this->errorMessage): ?>
                    <div class="error">

                            <h2>Notice</h2>


                            <dl id="system-message">
                                    <dt class="error">Error</dt>
                                    <dd class="error message">
                                            <ul>
                                                    <li><?php print $this->errorMessage; ?></li>
                                            </ul>
                                    </dd>
                            </dl>

                    </div>

		<?php endif; ?>
		<div class="login">
			<div class="login-description"></div>
			<?php print $this->form; ?>
		</div>

	</div>
</div>
