<form action="" method="post">
    <fieldset>
        <div class="login-fields">
            <label id="username-lbl" for="username" class=" required">Email<span class="star">&nbsp;*</span> </label> 
            <?php print $this->element->email; ?>
        </div>
        <button type="submit" class="button">Send</button>
        <input type="hidden" name="return"
               value="aW5kZXgucGhwP0l0ZW1pZD00NjQ="> <input type="hidden"
               name="f9d471479dcd6cdbf2762f6b8af6e97d" value="1">
    </fieldset>
</form>