<tr>
    <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->activity_id ?></td>
    <td><?php print $this->title ?></td>
    <td><?php print $this->link ?></td>
    <td class="options-width">
        <a href='/activities/edit/id/<?php echo $this->activity_id; ?>' class="icon-1 info-tooltip"></a>
        <a onclick="return confirm('Biztos benne?');" href="/activities/delete/id/<?php echo $this->activity_id; ?>" class="icon-2 info-tooltip"></a>
    </td>
</tr>