<tr>
    <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->cat_id ?></td>
    <td><?php print $this->category ?></td>        
    <td class="options-width">
        <a href='<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/gearscategory/edit/id/<?php echo $this->gears_category_id; ?>' class="icon-1 info-tooltip"></a>
        <a href='<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/gearssubcategory/list/categoryid/<?php echo $this->gears_category_id; ?>' class="icon-3 info-tooltip"></a>        
        <a onclick="return confirm('Biztos benne?');" href="<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/gearscategory/delete/id/<?php echo $this->gears_category_id; ?>" class="icon-2 info-tooltip"></a>
    </td>
</tr>                                            