<tr>
    <td><input type="checkbox" class="ui-helper-hidden-accessible"><span class="ui-checkbox"></span></td>
    <td><?php print $this->name; ?></td>
    <td><?php print $this->access_level; ?></td>
    <td><a href='/menuitem/index/menu/<?php echo $this->id;?>'>Menüelemek</a></td>
    <td class="options-width">
        <a href='/menu/edit/id/<?php echo $this->id; ?>' class="icon-1 info-tooltip"></a>
        <!--                                            <a href="" class="icon-3 info-tooltip"></a>
                                                        <a href="" class="icon-4 info-tooltip"></a>-->
        <a onclick="return confirm('Biztos benne?');" href="/menu/delete/id/<?php echo $this->id; ?>" class="icon-2 info-tooltip"></a>
    </td>
</tr>                                            