<tr>
    <td><input type="checkbox" class="ui-helper-hidden-accessible"><span class="ui-checkbox"></span></td>
    <td><?php print $this->name ?></td>
    <td><?php print $this->email ?></td>
    <td><?php print $this->date ?></td>
    <td><?php print $this->phone ?></td>
    <td><?php print $this->city ?></td>
    <td><?php print $this->age ?></td>
    <td class="options-width">
<!--        <a href='/user/update/id/<?php echo $this->id; ?>' class="icon-1 info-tooltip"></a>-->
        <!--                                            <a href="" class="icon-3 info-tooltip"></a>
                                                        <a href="" class="icon-4 info-tooltip"></a>-->
        <a onclick="return confirm('Biztos benne?');" href="/user/delete/id/<?php echo $this->id; ?>" class="icon-2 info-tooltip"></a>
    </td>
</tr>                                            