<tr>
	<td>&nbsp;</td>
	<td><?php echo $this->name ?></td>    	
	<td class="options-width">
		<a href="<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/page/edit/id/<?php echo $this->id;?>" title="Szerkesztés" class="icon-1 info-tooltip"></a>
		<a href="<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/page/delete/id/<?php echo $this->id;?>" title="Törlés" class="icon-2 info-tooltip"></a> 		
	</td>
</tr>