<tr>
    <td><input type="checkbox" class="ui-helper-hidden-accessible"><?php print $this->id ?></td>
    <td><?php print $this->user_username ?></td>
    <td><?php print $this->user_email ?></td>
    <td><?php print $this->user_role ?></td>
    <td class="options-width">
    <?php if($this->user_role=="user") { ?>
        <!-- <a href='/user/adminedit/id/<?php echo $this->user_id; ?>' class="icon-1 info-tooltip"></a> -->
        <?php if($this->user_active=="1") { ?>
        <a href="<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/user/deactive/id/<?php echo $this->user_id; ?>" class="icon-5-active info-tooltip"></a>
        <?php } else { ?>
        <a href="<?php print $this->baseUrl(); ?>/<?php print Zend_Registry::get('Zend_Locale'); ?>/user/active/id/<?php echo $this->user_id; ?>" class="icon-5 info-tooltip"></a>
        <?php } ?>
        <!--                                                <a href="" class="icon-4 info-tooltip"></a>-->                
        <a onclick="return confirm('Biztos benne?');" href="/user/delete/id/<?php echo $this->user_id; ?>" class="icon-2 info-tooltip"></a>
        <?php } ?>
    </td>
</tr>                                            