<noscript>A böngésződön nincs bekapcsolva a Javascript! Enélkül sajnos nem működik rendesen az oldal.</noscript>
<script language="javascript" type="text/javascript">
    function textCounter( field, countfield, maxlimit ) {
        if ( field.value.length > maxlimit )
        {
            field.value = field.value.substring( 0, maxlimit );            
            return false;
        }
        else
        {
            var kar = document.getElementById('char');
            kar.innerHTML = maxlimit - field.value.length;
        }
    }

    (function($){
        $.fn.extend({
            customStyle : function(options) {
                if(!$.browser.msie || ($.browser.msie&&$.browser.version>6)){
                    return this.each(function() {
                        var currentSelected = $(this).find(':selected');
                        $(this).after('<span class="customStyleSelectBox"><span class="customStyleSelectBoxInner">'+currentSelected.text()+'</span></span>').css({position:'absolute', opacity:0,fontSize:$(this).next().css('font-size')});
                        var selectBoxSpan = $(this).next();
                        var selectBoxWidth = parseInt($(this).width()) - parseInt(selectBoxSpan.css('padding-left')) -parseInt(selectBoxSpan.css('padding-right'));
                        var selectBoxSpanInner = selectBoxSpan.find(':first-child');
                        selectBoxSpan.css({display:'inline-block'});
                        selectBoxSpanInner.css({width:selectBoxWidth-100, display:'inline-block'});
                        var selectBoxHeight = parseInt(selectBoxSpan.height()) + parseInt(selectBoxSpan.css('padding-top')) + parseInt(selectBoxSpan.css('padding-bottom'));
                        $(this).height(selectBoxHeight).change(function(){
                            // selectBoxSpanInner.text($(this).val()).parent().addClass('changed');   This was not ideal
                            selectBoxSpanInner.text($(this).find(':selected').text()).parent().addClass('changed');
                        });
                    });
                }
            }
        });
    })(jQuery);

    $(document).ready(function(){
        $('#sex').customStyle();
        $('#activate').customStyle();
        $('#facebook').customStyle();
        $('#facebook_users').customStyle();
        $('#twitter').customStyle();
        $('#twitter_users').customStyle();
        $('#blog').customStyle();
    });

</script>
<form id="formElem" name="formElem" action="" method="post">
    <fieldset class="step">
        <div class="leftCol">
            <h2>1. lépés</h2>
            <p class="side">Kérjük, add meg személyes adataidat és elérhetőségedet, hogy további információkat küldhessünk Neked a későbbiekben a Mob!lers kampány kapcsán.</p>
        </div>
        <div class="rightCol">            
            <div class="formRow">
                <label for="username">Név*</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->name; ?></div>
                <div class="right"></div>
            </div>
            <div class="formRow">
                <label for="username">Nem*</label>                
                <?php print $this->element->sex; ?>                
            </div>
            <div class="formRow">
                <label for="username">Lakhely /város/ *</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->city; ?></div>
                <div class="right"></div>
            </div>
            <div class="formRow">
                <label for="phone">Kor *</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->age; ?></div>
                <div class="right"></div>
            </div>
            <button class="navi" id="2">Tovább</button>
        </div>
    </fieldset>
    <fieldset class="step">
        <div class="leftCol">
            <h2>2. lépés</h2>
            <p class="side">Kérjük, add meg személyes adataidat és elérhetőségedet, hogy további információkat küldhessünk Neked a későbbiekben a Mob!lers kampány kapcsán.</p>
        </div>
        <div class="rightCol">  
            <div class="formRow">
                <label for="phone">E-mail cím *</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->email; ?></div>
                <div class="right"></div>
            </div>
            <div class="formRow">
                <label for="phone">Telefon *</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->phone; ?></div>
                <div class="right"></div>
            </div>
            <div class="formRow">
                <label for="phone">Végzettség *</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->graduate; ?></div>
                <div class="right"></div>
            </div>
            <div class="formRow">
                <label for="activate">Az alábbiak közül mivel foglalkozol *</label>
                <?php print $this->element->activate; ?>
            </div>
            <button class="navi" id="3">Tovább</button>
            <button class="navi" id="2back">Vissza</button>
        </div>
    </fieldset>
    <fieldset class="step">
        <div class="leftCol">
            <h2>3. lépés</h2>
            <p class="side">Írd meg nekünk, hogy az online világban milyen felületeken vagy jelen és hány barátod, követőd van. </p>
        </div>
        <div class="rightCol">
            <div class="formRow">
                <label for="phone">Foglalkozás *</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->job; ?></div>
                <div class="right"></div>
            </div>
            <div class="formRow">
                <label for="facebook">Fent vagy Facebookon? *</label>
                <?php print $this->element->facebook; ?>
            </div>
            <div class="formRow">
                <label for="facebookUser">Hány ismerősöd van?</label>
                <?php print $this->element->facebook_users; ?>
            </div>      
            <button style="margin-top: 80px;" class="navi" id="4">Tovább</button>
            <button style="margin-top: 80px;" class="navi" id="3back">Vissza</button>
        </div>
    </fieldset>
    <fieldset class="step">
        <div class="leftCol">
            <h2>4. lépés</h2>
            <p class="side">Írd meg nekünk, hogy az online világban milyen felületeken vagy jelen és hány barátod, követőd van.</p>
        </div>
        <div class="rightCol">
            <div class="formRow" id="twitterBox">
                <label for="twitter">Fent vagy Twitteren? *</label>
                <?php print $this->element->twitter; ?>
            </div>
            <div class="formRow">
                <label for="twitter">Hány követőd van?</label>
                <?php print $this->element->twitter_users; ?>
            </div>
            <div class="formRow">
                <label for="blog">Van saját blogod? *</label>
                <?php print $this->element->blog; ?>
            </div>
            <div class="formRow">
                <label for="blog_address">Blogod címe</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->blog_address; ?></div>
                <div class="right"></div>
            </div>
            <button class="navi" id="5">Tovább</button>
            <button class="navi" id="4back">Vissza</button>
        </div>
    </fieldset>
    <fieldset class="step">
        <div class="leftCol">
            <h2>5. lépés</h2>
            <p class="side">Írd le, hogy magadról mit tartasz fontosnak, milyen vagy te, mindezt 160 karakterbe sűrítve. </p>
        </div>
        <div class="rightCol">
            <div class="formRow">
                <label for="blog_address">Kedvenc applikációd neve</label>
                <div class="left"></div>
                <div class="center"><?php print $this->element->app; ?></div>
                <div class="right"></div>
            </div>
            <div class="formRowTxtArea">
                <label for="bio">Írj magadról 160 karakterben! *
<!--                    <span class="note">(Írd le, milyen vagy! Írd le, milyennek tartanak Téged mások! Írd le, mit gondolsz a világról Írd le, miért lennél Te ideális Mob!ler! Olyat írj, amiből kiderül az egyéniséged és az írásbeli kommunikációs készséged.)</span>-->
                </label>
                <div class="leftTxtArea"></div>
                <div class="centerTxtArea"><?php print $this->element->bio; ?></div>
                <div class="rightTxtArea"></div>
            </div>
            <button class="navi" id="6">Tovább</button>
            <button class="navi" id="5back">Vissza</button>
        </div>
    </fieldset>
    <fieldset class="step" id="lastStep">
        <div class="leftCol">
            <h2>Befejezés</h2>
            <p class="side">A regisztráció véglegesítéshez olvasd el és fogadd el a képernyőn található Szabályzatot.</p>
        </div>
        <div class="rightCol">
            <p>A Samsung Mob!lers 2011-es kampányra (a továbbiakban: Kampány) történő jelentkezés automatikusan nem vonja maga után a kampányban történő részvételt is.
                -	A jelentkezők közül azon résztvevőket, akikkel a Samsung Electronics Magyar Zrt. (a továbbiakban: Samsung) és a lebonyolítást végző Ügynökség (a továbbiakban: Ügynökség) a Kampány során együttműködni kíván, egy a Samsung és Ügynökség munkatársaiból ezen célból létrejövő grémium választja ki. A kiválasztás a jelentkező által kitöltött online adatlapon megadott válaszok és adatok alapján történik.

                -	A kiválasztott személy (a továbbiakban: Mobiler) vállalja, hogy a Kampány során Samsunggal és Ügynökséggel együttműködik a Kampány sikeres lebonyolítása érdekében. Vállalja, hogy egy Együttműködési Nyilatkozat aláírásával bizonyos aktivitásokat elvégez a Kampány során.


                -	A Mobiler együttműködése nem eredményez foglalkoztatásra, munkavégzésre irányuló tevékenységet, annak nem minősül. A Mobiler az együttműködésért anyagi juttatásra nem tart igényt, azt nem kap.
            </p>           
                <p id="terms"><?php print $this->element->terms; ?> <span>Elfogadom a szabályzatot </span></p>
                           
            <button class="navi" id="6back" style="float: left !important; margin-top: 65px;">Vissza</button>
                <button id="regisztracio" type="submit" style="margin-top: 65px;">Regisztrálok</button>
           
        </div>
    </fieldset>
</form>

