<div id="content" class="content">
    <div id="wrapper">
        <div id="steps">
            <?php print $this->form; ?>
        </div>
        <div id="navigation" style="display:none;">
            <ul>
                <li class="selecteded">
                    <a id="1-nav" href="#">1. lépés</a>
                </li>
                <li>
                    <a id="2-nav" href="#">2. lépés</a>
                </li>
                <li>
                    <a id="3-nav" href="#">3. lépés</a>
                </li>
                <li>
                    <a id="4-nav" href="#">4. lépés</a>
                </li>
                <li>
                    <a id="5-nav" href="#">5. lépés</a>
                </li>
                <li>
                    <a id="6-nav" href="#">Befejezés</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div id="dialog-message" title="Hiba">
    <p>Kérlek töltsd ki helyesen az összes kötelező mezőt!</p>
</div>