<div id="admin-content">
    <div id="page-heading"><h1>Admin Page</h1></div>
    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
        <tbody><tr>
                <th rowspan="3" class="sized"><img src="<?php print $this->baseUrl(); ?>/public/admin/images/shared/side_shadowleft.jpg" width="20" height="300" alt=""></th>
                <th class="topleft"></th>
                <td id="tbl-border-top">&nbsp;</td>
                <th class="topright"></th>
                <th rowspan="3" class="sized"><img src="<?php print $this->baseUrl(); ?>/public/admin/images/shared/side_shadowright.jpg" width="20" height="300" alt=""></th>
            </tr>
            <tr>
                <td id="tbl-border-left"></td>
                <td>
                    <!--  start content-table-inner -->
                    <div id="content-table-inner">
                        <table border="0" width="100%" cellpadding="0" cellspacing="0">
                            <tbody><tr valign="top">
                                    <td colspan="2">
                                        <!-- start id-form -->
                                        <?php if($this->identity == null) { ?>
                                            <p>To log in <a href='/user/login'>click here</a></p>
                                        <?php }else{ ?>
                                            
                                        <?php } ?>
                                        <!-- end id-form  -->
                                        <br/>                                        
                                    </td>                                    
                                </tr>
                                <tr>
                                    <td><img src="/public/admin/images/shared/blank.gif" width="695" height="1" alt="blank"></td>
                                    <td></td>
                                </tr>
                            </tbody></table>


                    </div>
                    <!--  end content-table-inner  -->
                </td>
                <td id="tbl-border-right"></td>
            </tr>
            <tr>
                <th class="sized bottomleft"></th>
                <td id="tbl-border-bottom">&nbsp;</td>
                <th class="sized bottomright"></th>
            </tr>
        </tbody></table>
    <div class="clear">&nbsp;</div>
</div>